id: I1484887D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T02:35:21+00:00'
last_modified: '2022-06-08T03:32:06.567468+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD181195
  title: བཀའ་གཏེར་མན་ངག་རྒྱ་མཚོ་ཡི། །ལུང་རིག་མན་ངག་གི་གཏེར་མཛོད་བཞུགས༎
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    AB34:
      image_group_id: I1KG16379
      title: ''
      total_pages: 43
      order: 1
      base_file: AB34.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
