id: P005501
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD181195
  title: བཀའ་གཏེར་མན་ངག་རྒྱ་མཚོ་ཡི། །ལུང་རིག་མན་ངག་གི་གཏེར་མཛོད་བཞུགས༎
  author: ''
  volumes:
    9a23044a115b441db8f969860e83a197:
      image_group_id: I1KG16379
      title: ''
      volume_number: 1
      total_pages: 43
